apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricequote-deployment
  labels:
    app: pricequote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pricequote
  template:
    metadata:
      labels:
        app: pricequote
    spec:
      containers:
        - name: pricequote
           : deepz88/pricequote:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pricequote-service
spec:
  selector:
    app: pricequote
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080